import javax.swing.JOptionPane;
import javax.swing.ImageIcon;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Lenovo
 */
public class RadioButtonDemo1 extends javax.swing.JFrame {

    /**
     * Creates new form RadioButtonDemo1
     */
    public RadioButtonDemo1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        petGroup = new javax.swing.ButtonGroup();
        Bird = new javax.swing.JRadioButton();
        Cat = new javax.swing.JRadioButton();
        Dog = new javax.swing.JRadioButton();
        Rabbit = new javax.swing.JRadioButton();
        Pig = new javax.swing.JRadioButton();
        petLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        petGroup.add(Bird);
        Bird.setText("Bird");
        Bird.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BirdActionPerformed(evt);
            }
        });

        petGroup.add(Cat);
        Cat.setText("Cat");
        Cat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CatActionPerformed(evt);
            }
        });

        petGroup.add(Dog);
        Dog.setText("Dog");
        Dog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DogActionPerformed(evt);
            }
        });

        petGroup.add(Rabbit);
        Rabbit.setText("Rabbit");
        Rabbit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RabbitActionPerformed(evt);
            }
        });

        petGroup.add(Pig);
        Pig.setText("Pig");
        Pig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PigActionPerformed(evt);
            }
        });

        petLabel.setPreferredSize(new java.awt.Dimension(200, 200));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Bird, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Cat, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Dog, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Rabbit, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Pig, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 128, Short.MAX_VALUE)
                .addComponent(petLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(petLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Bird)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Cat)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Dog)
                        .addGap(18, 18, 18)
                        .addComponent(Rabbit)
                        .addGap(18, 18, 18)
                        .addComponent(Pig)))
                .addContainerGap(189, Short.MAX_VALUE))
        );

        petLabel.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BirdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BirdActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "You selected: Bird"); 
        petLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bird.jpg")));
    }//GEN-LAST:event_BirdActionPerformed

    private void CatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CatActionPerformed
      JOptionPane.showMessageDialog(this, "You selected: Cat"); 
      petLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cat.jpg")));
    }//GEN-LAST:event_CatActionPerformed

    private void DogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DogActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "You selected: Dog"); 
        petLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dog.jpg")));
    }//GEN-LAST:event_DogActionPerformed

    private void RabbitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RabbitActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "You selected: Rabbit"); 
        petLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/rabbit.jpg")));
    }//GEN-LAST:event_RabbitActionPerformed

    private void PigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PigActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "You selected: Pig"); 
        petLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/pig.jpg")));
    }//GEN-LAST:event_PigActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RadioButtonDemo1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RadioButtonDemo1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RadioButtonDemo1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RadioButtonDemo1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RadioButtonDemo1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Bird;
    private javax.swing.JRadioButton Cat;
    private javax.swing.JRadioButton Dog;
    private javax.swing.JRadioButton Pig;
    private javax.swing.JRadioButton Rabbit;
    private javax.swing.ButtonGroup petGroup;
    private javax.swing.JLabel petLabel;
    // End of variables declaration//GEN-END:variables
}
